apiVersion: v1
kind: Namespace
metadata:
  name: php-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: php-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: php-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: event_platform
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: userpassword

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/database.sql
              subPath: database.sql
      volumes:
        - name: init-sql
          hostPath:
            path: /home/maryem/event-registration/init-db
            type: Directory
