apiVersion: v1
kind: Namespace
metadata:
  name: php-mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  namespace: php-mysql
data:
  database.sql: |
    CREATE DATABASE IF NOT EXISTS event_platform;
    USE event_platform;
    -- Création de la table des participants
    CREATE TABLE IF NOT EXISTS participants (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nom VARCHAR(100),
      email VARCHAR(100),
      telephone VARCHAR(20),
      evenement VARCHAR(100),
      date_inscription TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Données de test
    INSERT INTO participants (nom, email, telephone, evenement) VALUES
    ('maryemzahmoul', 'maryem@example.com', '22222222', 'Conférence IA'),
    ('ameniamri', 'ameni@example.com', '12345678', 'Atelier DevOps');
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: php-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: php-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: event_platform
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: userpassword

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/database.sql
              subPath: database.sql
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init-sql
