apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: php-mysql
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
    - port: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: php-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php
          image: php-event-app:latest
          ports:
            - containerPort: 80
