

name: Déploiement Automatique kubernetes


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

     #Étape1: récuperation du code 
    - name: Checkout de code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

     #Étape2: Installer Kubectl
    - name: Installer kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.33.1'

     #Étape5: Build et Push Docker
    - name: Build & Push Docker Image
      run: |
        echo " Construction de l'image Docker "
        eval $(minikube docker-env)
        docker build -t zahmoul/event-registration:latest ./php-app
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{secrets.DOCKER_USERNAME }}" --password-stdin
        docker push zahmoul/event-registration:latest
        echo " Image Docker pushée "

    #Étape6: Déploiment kubernetes 
    - name: Déployer sur cluster local via ssh
      run: |
        sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no maryem@192.168.49.2 "
          cd ~/eveny-registration
          echo "Application des manifest kubernetes..."
          kubectl apply -f k8s/ --namespace=php-mysql
          # attendre que les pods soient prét
          echo "attente de deploiement mysql ..."
          kubectl wait --for=condition=ready pod -l app=mysql -n php-mysql --timeout=300s
          echo "attente de deploiement php ..."
          kubectl wait --for=condition=ready pod -l app=php-app -n php-mysql --timeout=300s
          echo "déploiement terminé"
       "

    #Etape7: Verification Finale
    - name: Vérification du déploiement
      run: |
        echo "=== État des ressources dans php-mysql ==="
        kubectl get all -n php-mysql

        echo "=== Détail de services ==="
        kubectl get services -n php-mysql

        echo "=== URL d'accés a l'application ==="
        minikube service -n php-mysql list


    #Etape8: Notification Succés
    - name: Notification Succés
      if: success()
      run: |
        echo " DÉPLOIEMENT RÉUSSI "
        echo " APPLICATIONS DEPLOYÉE AVEC SUCCÉS "
        echo "Pour accéder a l'application: minikube service php-service -n php-mysql"
